[tox]
env_list =
    py313-lint
    py3{10,11,12}-tf{218,219,220}
    py3{10,11,12}-tf{218,219,220}-torch{25}
    py3{10,11,12,13}-tf{220}-torch{210}
    py3{13}-tf{220}

[testenv]
description = Run tests with different TensorFlow versions
constrain_package_deps = true
setenv =
    XDG_CACHE_HOME = {toxworkdir}/cache
    PIP_CACHE_DIR = {toxworkdir}/pip_cache
    UV_CACHE_DIR = {toxworkdir}/uv_cache
deps =
    pytest
    pytest-cov
    tf218: tensorflow==2.18.0
    tf219: tensorflow==2.19.0
    tf220: tensorflow==2.20.0
package = editable
commands = pytest --cov=xplique --ignore=tests/wrappers/test_pytorch_wrapper.py --ignore=tests/concepts/test_craft_torch.py --ignore=tests/example_based/test_torch.py --disable-warnings --no-cov {posargs}

[testenv:py3{10,11,12,13}-tf{218,219,220}-torch{25}]
description = Run tests on PyTorch wrapper with different TensorFlow and PyTorch versions
deps =
    {[testenv]deps}
    torch25: torch==2.5.0
commands = pytest --cov=xplique tests/wrappers/test_pytorch_wrapper.py tests/concepts/test_craft_torch.py tests/example_based/test_torch.py --disable-warnings --no-cov {posargs}

[testenv:py3{10,11,12,13}-tf{220}-torch{210}]
description = Run tests on PyTorch wrapper with different TensorFlow and PyTorch versions
deps =
    {[testenv]deps}
    torch210: torch==2.10.0
commands = pytest --cov=xplique tests/wrappers/test_pytorch_wrapper.py tests/concepts/test_craft_torch.py tests/example_based/test_torch.py --disable-warnings --no-cov {posargs}

[testenv:py313-lint]
description = Run linters on the codebase
deps =
    ruff
commands =
    ruff check xplique
    ruff format xplique --check
skip_install = true
