name: "Build and Publish Latest Release Docs"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Documentation version to deploy"
        required: true
        type: string

permissions:
  contents: write

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: "Set up uv"
        uses: astral-sh/setup-uv@v6

      - name: "Install Documentation Dependencies"
        run: |
          uv pip install --system --group docs
          uv pip install --system --no-deps .

      - name: "Setup Docs Deploy"
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: "Deploy Github Pages"
        env:
          DOCS_VERSION: ${{ github.event.release.tag_name || inputs.version }}
        run: |
          mike delete latest
          mike deploy --update-aliases "$DOCS_VERSION" latest
          mike set-default latest
          git push origin gh-pages
