name: tests for torch

on:
  push:
    branches:
      - lucas/torch
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        include:
            - python-version: 3.8
              tf-version: 2.5
              torch-version: 1.11
            - python-version: 3.8
              tf-version: 2.8
              torch-version: 1.11
            - python-version: 3.8
              tf-version: 2.11
              torch-version: 1.11
            - python-version: 3.9
              tf-version: 2.8
              torch-version: 1.13
            - python-version: 3.9
              tf-version: 2.11
              torch-version: 1.13
            - python-version: "3.10"
              tf-version: 2.8
              torch-version: 2.0.0
            - python-version: "3.10"
              tf-version: 2.11
              torch-version: 2.0.0

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox (Python ${{ matrix.python-version }} - TF ${{ matrix.tf-version }} - PyTorch ${{ matrix.torch-version }})
      run: tox -e py$(echo ${{ matrix.python-version }}-tf${{ matrix.tf-version }}-torch${{matrix.torch-version}} | tr -d .)
